from snakemake.utils import min_version
import pandas as pd

##### set minimum snakemake version #####
min_version("9.16.2")

family = config["run"]["family"]
samples = pd.read_table(config["run"]["samples"], dtype=str).set_index("sample", drop=False)

##### load rules #####
include: "rules/common.smk"
include: "rules/annotate_STRs.smk"
include: "rules/svreport.smk"
include: "rules/cnvreport.smk"
include: "rules/annotate_sequence_var.smk"
include: "rules/annotate_mt_var.smk"

if config["run"]["mt_report"] == "mt":
    base = "rules/"
    include: base + "annotate_mt_var.smk"


if config["run"]["mt_report"] == "mt":
    rule all:
        input:
            "reports/mitochondrial/{family}.mitochondrial.report.csv".format(family=family)
else:
    rule all:
        input:
            "sequence_variants/coding/{family}".format(family=family),
            "reports/{family}.known.path.str.loci.csv".format(family=family),
            "reports/{family}.sv.csv".format(family=family),
            "reports/{family}.cnv.csv".format(family=family),
            "reports/mitochondrial/{family}.mitochondrial.report.csv".format(family=family)