from snakemake.utils import min_version
import pandas as pd

##### set minimum snakemake version #####
min_version("9.16.2")

def get_children_ids(ped_file):
    pedigree = pd.read_csv(ped_file, sep="\t", header=None, 
                          names=["family_ID", "individual_ID", "paternal_ID", "maternal_ID", "sex", "phenotype"])
    pedigree = pedigree.astype(str)
    children = pedigree[pedigree["paternal_ID"] != "0"][pedigree["maternal_ID"] != "0"]["individual_ID"].apply(lambda x: x.split("_")[1]).values
    family = pedigree["family_ID"].iloc[0]

    return children

family = config["run"]["family"]
samples = pd.read_table(config["run"]["samples"], dtype=str).set_index("sample", drop=False)
if config["run"]["ped"]:
	children = get_children_ids(config["run"]["ped"])
else:
    children = []


##### load rules #####
include: "rules/common.smk"
include: "rules/annotate_STRs.smk"
include: "rules/svreport.smk"
include: "rules/cnvreport.smk"
include: "rules/annotate_sequence_var.smk"
include: "rules/annotate_mt_var.smk"
include: "rules/qc.smk"
include: "rules/compound_hets.smk"


family = config["run"]["family"]
samples = pd.read_table(config["run"]["samples"], dtype=str).set_index("sample", drop=False)

rule all:
    input:
        "reports/{family}.wgs.coding.CH.hg38.csv".format(family=family),
        "reports/{family}.panel.CH.hg38.csv".format(family=family),
        "reports/{family}.panel-flank.CH.hg38.csv".format(family=family),
        "reports/{family}.wgs.high.impact.CH.hg38.csv".format(family=family),
        "reports/{family}.wgs.denovo.CH.hg38.csv".format(family=family) if len(children) > 0 else [],
        "reports/{family}.known.path.str.loci.hg38.csv".format(family=family),
        "reports/{family}.sv.CH.hg38.csv".format(family=family),
        "reports/{family}.cnv.CH.hg38.csv".format(family=family),
        "reports/{family}.mito.hg38.csv".format(family=family),
        "reports/{family}.multiqc_report.html".format(family=family),
        "reports/{family}.compound.het.status.CH.hg38.csv".format(family=family)
