run:
  family: "FAM-000000"
  samples: samples.tsv
  units: units.tsv
  hpo: "" # proband-specific HPO terms
  ped: ""
  mt_report: "" # specify "mt" to pull MT variants from Dragen VCF, annotate, and generate mitochondrial reports. Leave blank to ignore
  

tools:
  cphi-dragen-anno: "~/CPHI-DRAGEN-anno/"
  annotSV: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/crg2-pacbio-non-conda-tools/AnnotSV-3.1.1"
  cre: "~/CPHI-DRAGEN-anno/workflow/scripts/cre"
  mity: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/crg2-non-conda-tools/mity_v2.0.1/bin"


ref:
  name: "GRCh38.115"
  genome: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/genomes/DRAGEN_hg38-fasta-0-1_graph/hg38.fa"
  known-variants: "/hpf/largeprojects/ccmbio/nhanafi/c4r/genomes/Homo_sapiens_assembly38.dbsnp138.vcf"
  canon_bed: "/hpf/largeprojects/ccmbio/nhanafi/c4r/genomes/illumina/grch38_canon.bed"

params:
  snpeff:
    java_opts: "-Xms750m -Xmx20g"

annotation:
  mity:
    report_config: "~/CPHI-DRAGEN-anno/workflow/wrappers/vcfanno/mity/report-config.yaml"
    vcfanno_config: "~/CPHI-DRAGEN-anno/workflow/wrappers/vcfanno/mity/vcfanno-config-mt.toml"
    base_path: "/hpf/largeprojects/ccmbio/nhanafi/c4r/downloads/databases/mity/"
  snpeff:
    data_dir: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation_hg38/snpEff/data"
    config: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation_hg38/snpEff/snpEff.config"
  omim_path: "~/crg2-pacbio/scripts/cre/data/"
  general:
    exon: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation_hg38/DRAGEN_genes/MANE/MANE.GRCh38.v1.5.ensembl_genomic.bed"
    ensembl: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation_hg38/DRAGEN_genes/ensembl/Homo_sapiens.GRCh38.115.chr.processed.csv"
    adotto_repeats: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation_hg38/repeats/repeat_catalogs_for_TRGT/adotto_repeats.hg38.bed"
    clingen_path: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation_hg38/ClinGen/"
  sv_report:
    gnomad_SV: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation_hg38/gnomAD/v4.1/SV/gnomad.v4.1.sv.sites.processed.bed"
    dgv: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation_hg38/DGV/DGV.GS.hg38.tsv"
    1000G_SV: "/hpf/largeprojects/ccmbio/students/rkhan/cphi_dragen_runs/1000g/1000g_database/1000G.1000G_SV_database_AF.bed"
  vep:
    dir: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/snakemake/499f2ad2/share/ensembl-vep-115.2-0/"
    dir_cache: "/hpf/largeprojects/ccmbio/nhanafi/c4r/downloads/databases/vep"
    phyloP100way: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation_hg38/PhyloP100way/hg38.phyloP100way.bw"
  vcfanno:
    conf: "~/CPHI-DRAGEN-anno/resources/vcfanno/vcfanno.conf"
    lua_script: "~/CPHI-DRAGEN-anno/resources/vcfanno/vcfanno.lua"
    base_path: "/hpf/largeprojects/ccmbio/nhanafi/c4r/downloads/databases/"
  str_disease_thresholds: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation/ExpansionHunter/tandem_repeat_disease_loci_v1.1.3.tsv"
  cre:
    database_path: "/hpf/largeprojects/ccmbio/nhanafi/c4r/downloads/databases/"
