run:
  family: "FAM-000000"
  samples: samples.tsv
  units: units.tsv
  hpo: "" # proband-specific HPO terms
  ped: ""

tools:
  cphi-dragen-anno: "~/CPHI-DRAGEN-anno/"

annotation:
  str_disease_thresholds: "/hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation/ExpansionHunter/tandem_repeat_disease_loci_v1.1.3.tsv
